name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          version: 10.8.0

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Lint admin
        run: pnpm admin:lint

      - name: Lint web
        run: pnpm web:lint

      - name: Build admin
        run: pnpm admin:build

      - name: Build web
        run: pnpm web:build

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests (admin-e2e)
        run: pnpm --filter admin-e2e exec playwright test

      - name: Run Playwright tests (web-e2e)
        run: pnpm --filter web-e2e exec playwright test

      - name: Upload Playwright Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
